use_nerdfont = true

[theme]
background = "default"
primary = "#C0C0C0"
secondary = "#808080"
title = "#93E0E3"
playing = "#DFAF8F"
playing_selected = "#93E0E3"
playing_bg = "#383838"
highlight = "#E0CF9F"
highlight_bg = "#323232"
error = "#404040"
error_bg = "#DCA3A3"
statusbar = "#404040"
statusbar_progress = "#ABABAB"
statusbar_bg = "#7CB8BB"
cmdline = "#E0CF9F"
cmdline_bg = "#404040"
